### ISSUE TITLE
Problema integración grupo Verificación

### ISSUE THREAD

**Issue by danjimgar** [abayta/EGC-Modificacion#1]
En la pasada integración hemos tenido un problema con el Grupo de Verificación ya que no hemos podido utilizar sus librerías en nuestro proyecto.

**Comment by danjimgar** [comment]
Hemos preguntado al subsistema involucrado con el error y nos ha comentado que lo van a solucionar lo más pronto posible, como mucho el miércoles.

**Comment by Gabvaztor** [comment]
Un compañero del grupo de verificación me ha comentado esta mañana que ya han resuelto el error en la librería y lo han vuelto a subir a su repositorio. Sólo queda probarlo.
